yymin1022/Wa_API

- message.py
> Update message.py : Add Message Function Baby

- message.py
> Update meessage.py : Add more message in WA!

- message.py
> Update meme.py : Add more AH HA!

- message.py
> Update message.py : Add new function, Okay

- message.py
> Update message.py: Add new function for ROKA Kim

- message.py
> Update meme.py : New random message in WA

- message.py
Signed-off-by: Kim Byeongcheol <kbc20000@gmail.com>
> Update message.py: Add new function, Hungry

- message.py
Signed-off-by: Kim Byeongcheol <kbc20000@gmail.com>
> Update message.py: Disable some memes in function temporarily

- message.py
* Set the structure of new function without using if/elif.
Signed-off-by: Kim Byeongcheol <kbc20000@gmail.com>
> Update message.py: Add new function, Graduate

- message.py
Signed-off-by: Kim Byeongcheol <kbc20000@gmail.com>
> Update message.py: Add new function, Shuk

- message.py
* Hokyu is center of meme in South Korea LMAO XD
> Update meme.py: Stop auto calculating Hokyu's Military service & add more somethings

- message.py
* This developer always sleepy, So It must add in WA BOT!
> Update meme.py: Add new function Sleepy

- message.py
> Update meme.py: Add more function in Hokyu

- message.py
* One function 'messageHokyu' is divided into two functions 'messageHokyu' and 'messageHokyuJeonyeuk'
* He is an Korea Air Force soldier.
Signed-off-by: alienatiz <kbc20000@gmail.com>
> Update message.py: Redesign message function Hokyu

- message.py
* Change Hokyu's rank to private soldier
* HokyuGraduate: Add new message and increase the randInt value
Signed-off-by: Byeongcheol Kim <kbc20000@gmail.com>
> Update message.py: Change some messages of functions related with Hokyu

- message.py
- Military and Yongmin(Dev) related Commands has been removed.
- Corona Rule related Command has been removed : Korea has Removed rule.
> Removed some Command

- message.py
> Update message.py : Add Moloo Message Command

- .idea/workspace.xml
- message.py
Wa Sans!
I will Refactor later
> Added CAU Library Function

- .idea/workspace.xml
- message.py
> Update message.py : Add Joohyeong Message Function

- .idea/workspace.xml
- message.py
CAULibrary, CAUMeal 메시지 함수 Refactoring 완료
> CAU 기능 Rafactoring

- message.py
Signed-off-by: Byeongcheol Kim <kbc20000@gmail.com>
> Update message.py: Change class in function Hokyu

- message.py
> 남서울대 학식 기능 추가

- message.py
> 최땡민 코드 수정 및 김창환 입대일 추가

- message.py
시간 맞출려고 pytz 써봤는데 코드가 오지게 더러워져서 그냥 시간에서 9를 뺐습니다...
> 이땡수씨 9시간 조기출소하게끔 코드 수정

- message.py
> Update keyword line

- message.py
> modify eat

- main.py
- requirements.txt
CORS 정책을 적용하였습니다.
- Chrome 최신버전에서, CORS 정책이 적용되지 않은 서버의 응답이 정상적으로 전달되지 않는 문제가 있습니다.
- 모든 Origin에 대해 응답을 허용하도록 CORS 정책을 적용하였습니다.
> [FIX] CORS 정책 적용

- message.py
가짜뉴스 생성 기능 넣었읍니다.
일단 호출 키워드는 !뉴스로 해놨는데 수정 필요하면 comment 부탁드립니다.
> 가짜뉴스 호출 메시지 키워드 추가

- message.py
해당 부분 수정해서 
뉴스 제목: ~~~
본문: ~~~
형태로 출력되도록 했습니다.
> 버그 수정-뉴스 Return 문자열

- message.py
> 개행 문자 수정-제목,본문 따로

- message.py
Reduce the hansu Graduate function time due to server time zone change in Wa_API
Revise lefthours of 568th line (24 - now.hour - 10 to 24 - now.hour - 1)
> Modifying code according to time zone changes on the server

- message.py
- 호규 관련 메세지 업데이트함
- 김호규씨의 임기제 부사관 지원을 응원하는 뜻에서 기존의 메세지들을 수정함
> Update message.py: Hokyu Message Update

- message.py
- "자라" 메시지에 대한 응답에 대한 개선작업입니다.
- `messageZara()` 함수 내부에 2개 응답을 추가로 구현하였습니다.
> [DEV] "자라" 메시지 기능 개선작업

- message.py
- "!기억" 키워드만 작성 시 Wa API에서 정상적인 값을 return하지 않는 문제 해결
- "!기억" 단어를 날린 message string이 길이가 0인 경우 pass하게끔 코드 개선
> "뭐였지" 버그 수정

- message.py
- "성민 소해"를 입력했을 때 표시되는 내용을 추가합니다.
- 랜덤 함수의 범위를 5로 증가
- 변수 추가 (현재 시간 및 현재 시간을 기준으로 남은 시간, 분, 초를 계산)
- 변수 반환 일부 구분 lint
> 성민 소해 항목 추가

- message.py
- 전역과 소해, 졸업일 계산 기능은 기본적으로 거의 동일한 코드를 공유해서 사용했었는데, 이걸 함수 하나로 묶어서 처리하게끔 구조를 변경함.
- 한수, 성민, 재민, 승범, 호규의 코드를 messageGraduateDate() 함수를 거치게끔 해서 코드의 중복된 라인을 대폭 줄임.
- 병희, 창환, 호규의 코드의 불필요한 파트를 제거해서 최대한 간소하게 줄임.
> "전역&소해&졸업 시리즈" 코드 최적화

- message.py
- 성민 소해의 메시지를 업데이트 합니다.
- #86 에서 변경된 메시지를 반영합니다.
> 성민 소해 메시지 업데이트

- message.py
- 거북이를 호출하면 표시되는 메시지를 분리합니다.
- 몸통박치기와 물대포 메시지를 2개로 표시되도록 분리
- 스킬 메시지를 변수화 해서 최적화
> 거북이 메시지 분리

- .gitignore
- message.py
- D-Day 계산기 추가
- 함수 이름 변경
- !메모 기능 추가
- gitignore 파일 추가
- D-Day 계산기를 추가했습니다.
- 사용 예) !디데이 23.01.01 or !day 2023.01.01
- 연도를 20xx가 아닌 xx로만 입력한 경우, 글자 수를 체크해서 알아서 앞에 20을 붙이게끔 코드를 작성했습니다.
- 입력 형식을 지키지 않았을 경우 사용 예를 안내하도록 코드를 작성했습니다. 
- 날짜 계산 함수를 단순히 소해&전역일 계산기로만 사용하던 기존과 달리, 이제는 D-Day 계산기로도 사용되기 때문에 함수의 이름을 다음과 같이 변경했습니다.
- messageGraduateDate -> messageDateCalculator
- !메모 기능을 추가했습니다.
- 사용 예) !메모 아 집가고싶다
- 호출 키워드는 '뭐더라'입니다.
- 기본적인 동작 메커니즘은 !기억과 동일하나, !메모는 방을 기준으로 하는 것이 아니라 채팅 발신자의 이름을 기준으로 저장하므로 한 방 안에서 여러 사람이 사용하더라도 중복되지 않는다는 장점이 있습니다.
- 이론상 Wa API가 지원하는 모든 플랫폼에서 사용중인 이름이 동일하다면 플랫폼에 구애받지 않고 사용하는 것이 가능합니다.
(카톡에서 !메모 기능으로 내용을 저장한 뒤 텔레그램에서 '뭐더라'로 저장한 내용을 불러오기 등등..)
- API 테스트 과정에서 사용&생성된 파일들이 Git에 Add되지 않게 .gitignore 파일을 수정했습니다.
> D-Day 계산기 & !메모 기능 구현 등,,

- message.py
- 디데이 계산기와 !기억 기능 개선
- 한수 호규 멘트 추가
- 디데이 계산기 기능 개선
- 디데이가 음수(과거)인 경우 다른 멘트가 나오게끔 코드 수정
- 존재하지 않는 날짜(ex. 24.09.31), 사용 불가능한 형식(ex. 24.-9.1)에 대한 예외처리 추가
- 날짜도 초 단위처럼 세자리마다 콤마로 끊어서 나오도록 코드 수정
- 전체적으로 문장이 매끄럽도록 수정
- !기억 기능에서 !기억해 키워드도 삭제하게끔 코드 개선
> 디데이 계산기, !기억 기능 개선 등

- message.py
- messageDDay() 함수 기능 개선
- messageMemo() 함수 기능 개선
- 찰스 전역 문구 수정
- D-DAY 기능에서 leftdays가 0이면 문구가 정상적으로 출력되지 않던 문제 해결
- leftdays가 0이면 D-DAY라고 알리는 기능 추가
- 메모 기능에서 "!메모" 문자열을 제거할 때 뒤에 띄어쓰기가 있을 경우 그것도 제거하도록 기능 개선
- 기존에 입대일 전역일중 하나를 랜덤으로 띄워주던 방식에서 동시에 모두 보여주는 쪽으로 기능 개선
> 기능 관련 유지보수

- message.py
- BHGraduate 함수 수정
- 임병희씨의 요청에 따라 입대일을 기준으로 지난 날짜도 보여주게끔 코드를 수정함
> add function; BHGraduate

- message.py
- 호규 전역 멘트를 수정했습니다.
- 호규가 전역하게 됨에 따라 "호규 전역" 키워드 반응시 나오는 메세지를 수정했습니다.
> 호1규 전역 멘트 수정

- message.py
- 마법의 소라고동 추가
- 사용자에게 입력을 받고 받은 메시지에서 `와 마법의 소라고동이시여, `라는 접두사를 제거 후 `question`에 질문을 저장합니다. 만약 `question`이 비어있다면 '말 해'를 반환합니다. 그렇지 않다면 `해`, `아마`, `안 돼`, `다시 한번 물어봐` 중 랜덤한 하나의 것을 반환합니다.
예)
- 입력:  마법의 소라고동이시여, 밥을 먹어도 될까요?
- 출력: 안 돼
- 입력: 아 마법의 소라고동이시여, 커피를 마셔도 될까요?
- 출력: 해
- 입력: 아 마법의 소라고동이시여, 버그가 고쳐질까요?
- 출력: 아마
- 입력: 아 마법의 소라고동이시여, 오늘 잠을 잘 수 있을까요?
- 출력: 다시 한번 물어봐
> 마법의 소라고동 추가

- message.py
comment: 날씨 수정하였고 현재온도, 구름, 날씨 설명, 압력, 습도를 나타내게 바꾸었음, python formatting 형식으로 바꾸었음
- Modify weather data display, Korean, English
- The weather data display has been modified.
Here's the code.
```python
def messageWeather():
weatherAPIUrl = "https://api.openweathermap.org/data/2.5/weather?id=1835847&appid=ea9e5f8d8e4aa2c798f8eb78f361d1b4"
requestSession = requests.Session()
requestSession.mount(weatherAPIUrl, DESAdapter())
text = requestSession.get(weatherAPIUrl)
text = text.text
jsonData = json.loads(text)
strMessage = "현재온도: " + str((jsonData["main"]["temp"])) +"K" + " 구름: " + str((jsonData["clouds"]["all"]))
strMessage += "\n현재 날씨는 " + str((jsonData["weather"]["description"]))
return strMessage
```
Modified part
```python
strMessage = "현재온도: {}K\\n구름: {}%\\n오늘의 날씨는 …
```
> [DEV] 날씨 기능 업데이트

- message.py
- 열람실 관련 이슈를 해결했습니다.
- 호규 전역 키워드 관련해서 수정했습니다.
- 제3 열람실의 현재 사용중인 좌석의 수가 제2 열람실의 것으로 잘못 불러와지는 이슈를 해결했습니다.
- 호규가 전역함에 따라 불필요해진 기능들을 정리했습니다.
> 남서울대 열람실 오류 해결 등 2개

- message.py
- 남서울대학교 학식 파서 기능 개선
- 남서울대학교의 학식을 불러오는 기능을 오늘 날짜에 해당하는 것만 불러오게 코드를 개선했습니다.
> 남서울대학교 학식 파서 기능개선

- message.py
- 택배관련 기능을 추가했습니다.
- 임병희 전역 관련 버그 진짜진짜 수정
- 롯데택배 조회기능을 추가했습니다.
- 택배 사용 가이드 기능을 추가했습니다.
- 임병희 전역 관련 기능을 진짜 수정했습니다.
> 택배 기능 추가 등 2건

- message.py
- Implement Base64 Encode/Decode Command (encoding with utf8)
- Add messageBase64Encode method for encoding message
- Add messageBase64Decode method for decoding message
> Implement base64 command

- message.py
messageBase64Encode 메서드에서 나타나는 오류 해결
바이트코드를 문자열 형태로 변환하여 오류를 해결했다.
> edit messageBase64Encode method

- Guide_EN.md
- Guide_JP.md
- Guide_KO.md
- message.py
- requirements.txt
- setupServer.sh
- 통관 관련 기능 수정
- 수필 소해 기능 추가
- README.md 파일 수정
- 통관 현황을 불러오는 기능에서 품목과 현황에 불필요한 태그가 같이 따라오는 문제를 해결했습니다.
- 운송장번호에 문자가 함께 오는 경우도 있을 수 있으므로 숫자만 들어있는지 검사하는 기능을 제거했습니다.
- 수필 소해 관련 기능을 추가했습니다.
- 필요한 모듈이 추가됐으므로 README.md 파일과 setupServer.sh 파일 등 필요한 모듈이 명시돼있는 파트를 수정했습니다.
- Ubuntu Server 20.04에서 setupServer.sh로 Wa API 서버를 구축할 시에 "bs4, flask_cors, waitress" 모듈이 누락돼 정상적인 실행이 불가한 문제를 해결했습니다.
- lxml 모듈 미설치시 정상적으로 실행이 불가한 문제를 확인했으므로 설치 모듈에 lxml을 추가시켰습니다.
// lxml 모듈 미설치시 //
// lxml 모듈 설치시 //
> 통관 관련 기능 수정 등

- Guide_EN.md
- Guide_JP.md
- Guide_KO.md
- message.py
- setupServer.sh
- setupServer.sh 스크립트 수정
- [setupServer.sh 스크립트의 의존성 이슈](https://github.com/yymin1022/Wa_API/issues/112)를 해결했습니다.
> setupServer.sh 스크립트 수정

- message.py
- 롯데택배 조회 기능에서 시간과 관련된 출력을 변경했습니다.
- 기존에는 날짜와 시간이 구분없이 붙어서 출력됐으나 이제는 공백으로 구분되어 출력됩니다.
> 롯데택배 시간 포맷 변경

- message.py
- 남서울대 학식 파서 함수를 수정했습니다.
- 학교의 홈페이지 구조가 변경됨에 따라 대응 업데이트를 진행했습니다.
> 남서울대학교 학식 파서 수정

- message.py
중앙대학교 학식 기능에 내일메뉴 보기 기능을 추가하였습니다.
- 기존에 존재하던 중앙대학교 학식 기능에 내일메뉴 보기 기능을 추가하였습니다.
- 메시지에 `내일` 키워드가 포함된 경우 내일 메뉴를, 그 외에는 오늘 메뉴를 반환합니다.
> [DEV] 중앙대 학식 내일

- main.py
- message.py
- 와봇의 전원과 관련된 기능이 정상 작동하지 않던 문제를 해결했습니다.
- power.json 파일이 존재하는 상태에서 파일 안에 방과 관련된 key값이 없는 경우...
1. 모든 메세지를 씹어버리는 문제를 해결했습니다.
2. 와봇을 켜려고 시도하는 경우 keyError가 발생하던 문제를 해결했습니다.
> 와봇 전원 기능 긴급 유지보수

- Jenkinsfile
- Jenkins Telegram Notification을 구성하였습니다.
- Telegram을 통한 Build 시작 및 결과 Notification 설정을 구성하였습니다.
> [DEV] Jenkins Notification 구성

- message.py
와봇이 '민석'키워드에 반응합니다!
```python
elif "민석" in message:
strResult = messageMinseok()
```
> [DEV] minseok 키워드 추가

- .gitignore
- apitest(direct).py
- apitest(flask).py
- message.py
- test.py
- Wa API를 테스트할 수 있는 코드를 추가했습니다.
- 이번에 추가한 코드는 다음과 같습니다.
i. apitest(direct).py // message.py 파일에 direct로 접근해서 응답 Message를 return 받습니다.
ii. apitest(flask).py // Wa API가 local에서 실제로 실행되고있는 상태에서 requests로 테스트 Message를 보내고, 응답을 return 받습니다.
- 각 코드의 설명입니다.
```python
import message
import os
import json
inputMessage = input("테스트 할 Message를 입력하세요: ") # 테스트할 Message를 입력받습니다.
replyMessage = message.getReplyMessage(inputMessage, "Test_Room1", "Test_Sender1") 
if replyMessage == "":
replyMessage = "None WA Bot Message Found"
elif "\\m" in replyMessage:
replyMessage = replyMessage.replace("\\m", "\n")
print(replyMessage)
```
```python
import requests
import json
def post():
url = "http://localhost/getMessage" # Message를 보낼 URL 정의
json_data = { # 보낼 Message를 정의
"msg": "와!",
"room": "아 1집가고싶다", …
```
> Wa API 테스트 프로그램 작성과 기타 수정사항

- .gitignore
- main.py
- message.py
- requirements.txt
Gemini API를 연동하였습니다.
- `잼민아`로 시작하는 메시지가 수신되면 Gemini API를 호출해 생성된 메시지를 반환합니다.
> [DEV] Gemini API 연동

- README.md
- You can check your project's interest by Hits badge.
- Add Hits badge in README
> [DOC] Add Hits badge in README

- message.py
random.choice를 이용해 많은 함수들 리펙토링했습니다.
- random.choice를 이용해 많은 함수들 리펙토링
- 약 200줄이 줄었습니다!
> [DEV] random.choice를 이용한 많은 함수들 리펙토링

- message.py
비트코인이 대화 내용에 있으면 시세가 출력됩니다!
- 사요?
> [DEV] Add bitcoin api

- message.py
- 재민소해, 택배 관련 기능 수정
- 재민이가 소집 해제됨에 따라 소해 관련 기능을 수정함
- 택배를 조회하는 기능을 보다 편하게 사용할 수 있게끔 키워드를 수정함
- (before) !택배 대통123456789 --> (after) !대통123456789
- 사용법 안내를 위해 !택배 기능 자체는 유지함
> 기능 수정 및 개선

- apitest(flask).py
- message.py
- 택배 조회기능을 더 간편하게 사용할 수 있게끔 개선함
- 기존의 '![택배사][운송장번호]' 방식을 '!택배[운송장]'으로 변경함
- Wa API에서 지원하는 모든 택배사를 하나씩 조회하면서 조회가 된 택배사의 message를 return함
> 택배 조회기능 개선

- message.py
통관조회 메시지의 오타를 수정하였습니다.
- 오타로 발생한 개행문자를 올바르게 처리하였습니다.
> [FIX] 통관조회 관련 오타수정

- Dockerfile
CAU 관련 기능의 SSL 이슈를 해결하였습니다.
- CAU 관련 기능의 SSL 이슈를 해결하고자, 기존 Docker Base 이미지를 `pytohn:3.10.6`에서 `ubuntu:20.04`로 변경하였습니다.
> [FIX] CAU SSL 이슈 해결

- message.py
SSL 이슈 해결 PR에 포함된 오타를 해결하였습니다.
> [FIX] SSL 이슈 해결 관련 핫픽스

- message.py
- 한수 소해 기능을 수정했습니다.
- 불필요한 기능 삭제 및 제대로 동작하지 않던 문제를 해결했습니다.
> 한수 소해 기능 수정

- message.py
- 유용민이 바보임을 입증하는 커맨드를 추가했습니다.
- 유용민 & 바보 -> 그렇지~
- 유용민 & 천재 -> 겠냐?
- 유용민 -> 바보~
Closes #141
> [DEV] 유용민 바보 특수 커맨드 추가

- message.py
- 택배 조회 기능을 수정했습니다
- 대한통운과 한진택배 한정으로 배송 현황을 파싱해올 때 제품명도 불러오도록 코드를 수정했습니다.
> 택배 조회 기능 추가

- message.py
- 용민과 관련한 커맨드 우선 순위를 변경했습니다.
- 기존 "용민" 키워드 존재
- "유용민" 키워드의 우선 순위를 높임
> [FIX] 유용민 커맨드 순서 변경

- message.py
- GDG 커맨드 추가
- "GDG on Campus: CAU 최고 ~!~!~!~!@"
- 우리는 최고니까 ~~~~~~~~ ㅎㅎ
> [DEV] GDG 최고 커맨드 추가

- message.py
- GDSC -> GDG 리브랜딩 
- "아뇨. GDG 인데요."
- "이제 GDG라니깐요?!"
- "GDG입니다."
- "GDSC는 이제 없어요."
- "GDG! GDG!! GDG!@!@!@!"
> [DEV] GDSC 아니라구요 커맨드 추가

- message.py
- 오타 수정
- GDSG -> GDG 로 오타 수정합니다 ...
> [FIX] GDSG -> GDG 오타 수정

- message.py
- 여진이 키워드 추가
- 여진 또는 김여진 키워드가 있을 시
["오나핑 여진이", "여진이 바빠요", "오거나이저!\m김여진!", "여지니 왜 불러요?\m난 왜 안 찾아?" ] 중
랜덤으로 메세지가 return 됩니다.
> [DEV] added yeojin keyword

- message.py
- 수현 키워드 추가
- 메세지 내에 '수현'이 있을 경우 '수현이? 무슨 수현이?\\m신수현? 임수현? 윤수현? 누구???' 다음과 같은 메세지 전송
> [DEV] soohyun keyword 추가

- message.py
- 수휫 키워드 if문 수정
- 수현 조건문에 수휫 추가
> [FIX] fix shweet logic

- message.py
비트코인 함수의 SSL 인증서 이슈를 해결하였습니다.
- `messageBitcoin` 함수의 SSL 인증서 이슈를 해결하였습니다.
- Request 옵션에 Certifi 인증서 검증을 추가하였습니다.
> [FIX] 비트코인 함수 SSL 이슈 해결

- message.py
- Vini함수와 Viki함수를 추가했어요!
- Vini 함수를 호출하면 디자이너 아니라는 내용이 나옵니다. 호출어는 유빈과 서유빈입니다람쥐. Viki는 운세예요. 호출어는 운세, 럭키비키 입니다.
---
> [DEV] Vini, Viki 함수 추가

- message.py
- 비니 비키 호출에 오타가 있었어요!!! 
- 싹 다 고쳐주었답니다~
> [FIX] Vini, Viki 함수 오타 수정

- message.py
GRF 밴드를 통해 개통한 회선의 정보 조회 기능을 추가하였습니다.
- GRF 밴드 개통 회선의 정보 조회 기능을 추가하였습니다.
- 개통이 완료되지 않은 회선인 경우 배송정보를, 개통이 완료된 회선인 경우 회선/요금제 유지기간이 표기되도록 하였습니다.
> [DEV] GRF 개통현황 조회 기능

- message.py
Gemini 관련 기능이 동작하지 않는 문제를 해결하고, 개선하였습니다.
- Gemini API 변경에 따라 기능이 동작하지 않는 문제를 해결하였습니다.
- 기존에 사용되던 `gemini-1.0-pro` 모델을 제거하고, `gemini-1.5-flash-8b` 모델로 변경하였습니다.
- 불필요한 Response 관련 옵션을 제거하였습니다.
- System Instruction을 이용해 Gemini 프롬프트를 최적화하였습니다.
> [FIX] Gemini 기능 관련 복구

- message.py
- 상윤, 동훈 추가
- 수현, 태환 수정
def messageSangyoon():
messages=[
"상윤아 트월킹 춰 줘",
"상윤아 잠 좀 자",
"상윤아 커피 좀 그만 마셔",
"알파 메일 김상윤!",
"똥훈아 따랑해",
"동훈이 보러가자!"
]
return random.choice(messages)
def messageDonghoon():
messages=[
"ㅋㅋ 동훈이 바보",
"상윤이는 내꺼야.",
"땅유나 따랑해",
"똥후니는 똑똑하고 귀엽고 잘생기고 멋지고 착해. 구치 애두랍~?",
"예. 저는 대졸입니다.",
"대학원 올래?"
]
return random.choice(messages)
def messageSoohyun():
strMessage = "수현이? 무슨 수현이?"
return strMessage
수현이 너무 긴거 지워버림
> [DEV] 상윤,동훈 추가 & 수현, 태환 수정

- message.py
- 상혁이 키워드추가
def messageSanghyuk():
messages = ["대.상.혁", "상혁아 이거 어떻게 해?", "적분의 신", "대대대"]
return random.choice(messages)
> [DEV] 상혁이 키워드 추가

- message.py
- 훈이 커맨트 추가했어요 ㅎㅎ
- 상혁이 "누나 미워" 추가
- 우리 훈이만 커맨드 없길래 추가했어요 ㅎㅎ
> [DEV] 훈 커맨드 추가, 상혁 메시기 추가

- message_util/message_command.py
#174  이후 발생하는 각종 이슈를 해결합니다.
- #174 이후 발생한 사소한 이슈들을 해결합니다.
- `message_command` Chopchop 함수 관련 SyntaxError
> [FIX] 모듈화 리팩토링 관련 이슈 해결

- message_util/message_command.py
환율 데이터를 조회하는 명령어를 구현하였습니다.
- 환율정보 API에 연동하여 각종 환율정보를 반환하는 명령어를 구현하였습니다.
- SMBS에서 제공하는 무료 API를 기반으로 동작합니다.
- 당일 실시간으로 발표된 환율 정보를 기준으로 하여, 시간대에 따라 보이는 정보의 양이 다를 수 있습니다.
> [DEV] 환율 명령어 구현

- message_util/message_graduate.py
- message_graduate 내의 message_tjo_graduate 함수를 수정했습니다.
- tjo가 공익 생활을 시작함에 따라 관련 기능을 업데이트 했습니다.
> [DEV] edit tjo function

- message.py
- message_util/message_gemini.py
Gemini LLM 호출 커맨드를 추가하였습니다.
- 기존 `잼민아` 키워드 이외에 일반적인 LLM 호출을 수행하는 커맨드를 추가하였습니다.
- `헤이구글` 키워드 이후의 메시지를 작성하면, 기존 모델과는 다른 일반 모델이 답변하도록 프롬프트를 작성하고, 모델을 지정하였습니다.
- `gemini-1.5-flash-latest` 모델을 기반으로 하여, 기존 `잼민아`에서 동작하는 모델보다는 응답이 조금 느릴 수 있지만 더 자세한 답변을 제공합니다.
> [DEV] Gemini LLM 커맨드 추가

- message_util/message_logistics.py
- test_util/test_util_flask.py
- 대한통운 파싱 관련 기능을 업데이트 했습니다.
- 기존에 파싱하는 데 사용하던 사이트가 곧 문을 닫는다고 하여 최신 사이트에 맞춰 기능을 업데이트 했습니다.
> [FIX] 대한통운 파싱 기능 업데이트

- message_util/message_gemini.py
탄력근무 계산 키워드를 추가합니다.
- `!탄력` 키워드로 동작하는 탄력근무 계산 키워드를 추가하였습니다.
- Gemini 기반으로 동작하며, 정해진 시스템 프롬프트를 작성하였습니다.
- `헤이구글` 및 `잼민아` 등, 모든 Gemini 기반 키워드의 기본 Gemini 모델을 `gemini-2.0-flash`로 변경하였습니다.
> [DEV] 탄력근무 계산 키워드 추가

- message_util/message_gemini.py
Gemini API에 기반해 동작하는 기능에 검색 그라운딩을 활성화하였습니다.
- `잼민아` 및 `헤이구글` 명령의 Gemini API 호출 시, Google 검색 그라운딩을 활성화하였습니다.
> [DEV] Gemini API 검색 그라운딩 활성화
